import type { TimeSlot } from "../models/TimeSlots";

const DemoTimeSlots: Record<string, TimeSlot[]> = {
  "1": [
    { id: "1", time: "08:00 AM", available: true },
    { id: "2", time: "08:30 AM", available: false },
    { id: "3", time: "09:00 AM", available: true },
    { id: "4", time: "09:30 AM", available: true },
    { id: "5", time: "10:00 AM", available: false },
    { id: "6", time: "10:30 AM", available: true },
    { id: "7", time: "11:00 AM", available: true },
    { id: "8", time: "11:30 AM", available: false },
    { id: "9", time: "12:00 PM", available: true },
    { id: "10", time: "12:30 PM", available: true },
    { id: "11", time: "01:00 PM", available: false },
    { id: "12", time: "01:30 PM", available: true },
    { id: "13", time: "02:00 PM", available: true },
    { id: "14", time: "02:30 PM", available: false },
    { id: "15", time: "03:00 PM", available: true },
    { id: "16", time: "03:30 PM", available: true },
    { id: "17", time: "04:00 PM", available: false },
    { id: "18", time: "04:30 PM", available: true },
    { id: "19", time: "05:00 PM", available: true },
    { id: "20", time: "05:30 PM", available: false },
    { id: "21", time: "06:00 PM", available: true },
  ],

  "2": [
    { id: "1", time: "08:00 AM", available: false },
    { id: "2", time: "08:30 AM", available: false },
    { id: "3", time: "09:00 AM", available: true },
    { id: "4", time: "09:30 AM", available: false },
    { id: "5", time: "10:00 AM", available: true },
    { id: "6", time: "10:30 AM", available: false },
    { id: "7", time: "11:00 AM", available: true },
    { id: "8", time: "11:30 AM", available: true },
    { id: "9", time: "12:00 PM", available: false },
    { id: "10", time: "12:30 PM", available: true },
    { id: "11", time: "01:00 PM", available: true },
    { id: "12", time: "01:30 PM", available: false },
    { id: "13", time: "02:00 PM", available: true },
    { id: "14", time: "02:30 PM", available: true },
    { id: "15", time: "03:00 PM", available: false },
    { id: "16", time: "03:30 PM", available: true },
    { id: "17", time: "04:00 PM", available: true },
    { id: "18", time: "04:30 PM", available: false },
    { id: "19", time: "05:00 PM", available: true },
    { id: "20", time: "05:30 PM", available: true },
    { id: "21", time: "06:00 PM", available: false },
  ],

  "3": [
    { id: "1", time: "08:00 AM", available: true },
    { id: "2", time: "08:30 AM", available: true },
    { id: "3", time: "09:00 AM", available: false },
    { id: "4", time: "09:30 AM", available: true },
    { id: "5", time: "10:00 AM", available: true },
    { id: "6", time: "10:30 AM", available: false },
    { id: "7", time: "11:00 AM", available: true },
    { id: "8", time: "11:30 AM", available: false },
    { id: "9", time: "12:00 PM", available: true },
    { id: "10", time: "12:30 PM", available: false },
    { id: "11", time: "01:00 PM", available: true },
    { id: "12", time: "01:30 PM", available: true },
    { id: "13", time: "02:00 PM", available: false },
    { id: "14", time: "02:30 PM", available: true },
    { id: "15", time: "03:00 PM", available: true },
    { id: "16", time: "03:30 PM", available: false },
    { id: "17", time: "04:00 PM", available: true },
    { id: "18", time: "04:30 PM", available: true },
    { id: "19", time: "05:00 PM", available: false },
    { id: "20", time: "05:30 PM", available: true },
    { id: "21", time: "06:00 PM", available: true },
  ],
}

export const getRoomTimeSlots = async (roomId: string): Promise<TimeSlot[]> => {
  await new Promise((resolve) => setTimeout(resolve, 400));
  return DemoTimeSlots[roomId] || [];
}